qlib_init:
    provider_uri: "~/.qlib/qlib_data/us_data"
    region: us

# NOTA: Definimos dos universos distintos.
market: &market sp500 # Todo el mercado para aprender
benchmark: &benchmark ^GSPC

data_handler_config: &data_handler_config
    start_time: 2018-01-01
    end_time: 2026-03-31
    instruments: *market
    data_loader:
        class: QlibDataLoader
        module_path: qlib.data.dataset.loader
        kwargs:
            config:
                feature:
                    # Definicion de factores
                    - [
                        "Resi($close, 15)/$close",
                        "(Ref($close, 5)-$close)/$close",
                        "Ref($close, 1)/$close",
                        "Mean($close, 20)/$close",
                        "Std($close, 20)/$close",
                        "100 - 100 / (1 + Mean(Greater(Delta($close, 1), 0), 14) / Greater(Abs(Mean(Less(Delta($close, 1), 0), 14)), 0.000001))",
                        "(Mean($close, 20) + 2 * Std($close, 20)) / $close",
                        "(Mean($close, 20) - 2 * Std($close, 20)) / $close",
                        "Mean($close, 20) / $close",
                      ]
                    - [
                        "ROC5",
                        "RET5",
                        "REF1",
                        "MEAN20",
                        "STD20",
                        "RSI14",
                        "BB_Upper",
                        "BB_Lower",
                        "BB_Middle",
                      ]
                label:
                    - ["Ref($close, -2)/Ref($close, -1) - 1"]
                    - ["label"]
            freq: day
    infer_processors:
        - class: RobustZScoreNorm
          kwargs:
            fit_start_time: 2018-01-01
            fit_end_time: 2023-12-31
            fields_group: feature
            clip_outlier: true
        - class: Fillna
          kwargs:
            fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm # Opcional: Normaliza los labels por ranking
          kwargs:
            fields_group: label

dataset_config: &dataset_config
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
        handler:
            class: DataHandlerLP
            module_path: qlib.data.dataset.handler
            kwargs: *data_handler_config
        segments:
            train: [2018-01-01, 2023-12-31]
            valid: [2024-01-01, 2024-12-31]
            test: [2025-01-01, 2026-03-31]

model_config: &model_config
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
        loss: mse
        colsample_bytree: 0.88
        learning_rate: 0.05
        subsample: 0.87
        lambda_l1: 1.5
        lambda_l2: 0.6
        max_depth: 10
        num_leaves: 100

record_config: &record_config
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        model: <MODEL>
        dataset: <DATASET>
    - class: SigAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        ana_long_short: False
        ann_scaler: 252
        label_col: 0

task:
    model: *model_config
    dataset: *dataset_config
    record: *record_config

experiment_name: config_analysis
