qlib_init:
  provider_uri: "~/.qlib/qlib_data/us_data"
  region: us

sys:
  rel_path: "."


market: &market sp500
benchmark: &benchmark SPY

data_handler_config: &data_handler_config
  start_time: 2008-01-01
  end_time: 2025-12-31
  fit_start_time: 2008-01-01
  fit_end_time: 2017-12-31
  instruments: *market

port_analysis_config: &port_analysis_config
  strategy:
    class: TopkDropoutStrategy
    module_path: qlib.contrib.strategy
    kwargs:
      signal: <PRED>
      topk: 50
      n_drop: 5

  backtest:
    start_time: 2021-01-01
    end_time: 2025-12-31
    account: 100000000
    benchmark: *benchmark
    exchange_kwargs:
      limit_threshold:
      deal_price: close
      open_cost: 0.0002
      close_cost: 0.0002
      min_cost: 1

task:
  model:
    class: AutoGluonQlibModel
    module_path: my_models.autogluon_qlib_model
    kwargs:
      label: LABEL0
      problem_type: regression
      eval_metric: root_mean_squared_error
      path: "./ag_models/us_alpha158"
      presets: medium_quality
      time_limit: 7200
      num_cpus: 16
      num_gpus: 0
      hyperparameters:
        GBM: {}
        CAT: {}
        XGB: {}
        RF: {}
        XT: {}

  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: Alpha158
        module_path: qlib.contrib.data.handler
        kwargs: *data_handler_config

      segments:
        train: [2008-01-01, 2017-12-31]
        valid: [2018-01-01, 2020-12-31]
        test:  [2021-01-01, 2025-12-31]

  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        model: <MODEL>
        dataset: <DATASET>

    - class: SigAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        ana_long_short: False
        ann_scaler: 252

    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        config: *port_analysis_config